[package]
name = "validator_change"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]

[dependencies]
bytes = "0.4.10"
hashing = { path = "../utils/hashing" }
types = { path = "../types" }
