#Adapted from https://users.rust-lang.org/t/my-gitlab-config-docs-tests/16396

image: 'sigp/lighthouse:latest'

stages:
  - test
  - doc

check-fmt:
  stage: test
  script:
    - cargo fmt --all -- --check

test-dev:
  stage: test
  script:
    - cargo test --verbose --all

test-release:
  stage: test
  script:
    - cargo test --verbose --all --release

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
      #    - echo '<meta http-equiv="refresh" content="0; url={{ LIBRARY NAME }}">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  paths:
    - /cargocache
    - target/
