language: rust
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - sudo chown $USER /usr/local/bin/protoc
  - sudo chown -R $USER /usr/local/include/google
env:
  - BUILD=
  - BUILD=--release
script:
  - cargo build --verbose $BUILD --all
  - cargo test --verbose $BUILD --all
  - cargo test --manifest-path eth2/state_processing/Cargo.toml --verbose --release --features fake_crypto
  - cargo fmt --all -- --check
  # No clippy until later...
  #- cargo clippy
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup component add rustfmt
  - rustup component add clippy
