language: rust
dist: xenial
before_install:
  - sudo apt-get install -y protobuf-compiler
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
