language: rust
cache:
  directories:
    - /home/travis/.cargo
# Going to try caching the registry
#before_cache:
#  - rm -rf /home/travis/.cargo/registry
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - sudo chown $USER /usr/local/bin/protoc
  - sudo chown -R $USER /usr/local/include/google
env:
  - BUILD=--all
# Not building --release on travis any more, only GitLab
#  - BUILD=--release --all
  - BUILD= --manifest-path eth2/state_processing/Cargo.toml --release --features fake_crypto
script:
  - cargo build --verbose $BUILD
  - cargo test --verbose $BUILD
  - cargo fmt --all -- --check
  # No clippy until later...
  #- cargo clippy
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  exclude:
# Not building --release on travis any more, only GitLab
#      - rust: beta
#        env: BUILD=--release --all
      - rust: beta
        env: BUILD= --manifest-path eth2/state_processing/Cargo.toml --release --features fake_crypto
# Not building --release on travis any more, only GitLab
#      - rust: nightly
#        env: BUILD=--release --all
      - rust: nightly
        env: BUILD= --manifest-path eth2/state_processing/Cargo.toml --release --features fake_crypto
install:
  - rustup component add rustfmt
# No clippy for now
#  - rustup component add clippy
