language: rust
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - sudo chown $USER /usr/local/bin/protoc
  - sudo chown -R $USER /usr/local/include/google
script:
  - cargo build --verbose --all --manifest-path lighthouse-beacon/Cargo.toml
  - cargo build --verbose --all --manifest-path lighthouse-validator/Cargo.toml
  - cargo build --verbose --all --manifest-path lighthouse-libs/Cargo.toml
  - cargo test --verbose --all --manifest-path lighthouse-beacon/Cargo.toml
  - cargo test --verbose --all --manifest-path lighthouse-validator/Cargo.toml
  - cargo test --verbose --all --manifest-path lighthouse-libs/Cargo.toml
  - cargo fmt --all -- --check --manifest-path lighthouse-beacon/Cargo.toml
  - cargo fmt --all -- --check --manifest-path lighthouse-validator/Cargo.toml
  - cargo fmt --all -- --check --manifest-path lighthouse-libs/Cargo.toml
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup component add rustfmt
