language: rust
git:
    submodules: false
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - sudo chown $USER /usr/local/bin/protoc
  - sudo chown -R $USER /usr/local/include/google
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
script:
  - cargo build --verbose --all --manifest-path lighthouse-beacon/Cargo.toml
  - cargo build --verbose --all --manifest-path lighthouse-validator/Cargo.toml
  - cargo build --verbose --all --manifest-path lighthouse-libs/Cargo.toml
  - cargo test --verbose --all --manifest-path lighthouse-beacon/Cargo.toml
  - cargo test --verbose --all --manifest-path lighthouse-validator/Cargo.toml
  - cargo test --verbose --all --manifest-path lighthouse-libs/Cargo.toml
  - cargo fmt --all --manifest-path lighthouse-beacon/Cargo.toml -- --check
  - cargo fmt --all --manifest-path lighthouse-validator/Cargo.toml -- --check
  - cargo fmt --all --manifest-path lighthouse-libs/Cargo.toml -- --check
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup component add rustfmt
