[package]
name = "lighthouse"
version = "0.0.1"
authors = ["Paul Hauner <paul@paulhauner.com>"]

[dependencies]
# TODO: remove "blake2" in favor of "blake2-rfc"
blake2 = "^0.7.1"
blake2-rfc = "0.2.18"
bls = { git = "https://github.com/sigp/bls" }
bytes = ""
crypto-mac = "^0.6.2"
clap = "2.32.0"
ethereum-types = ""
futures = "0.1.23"
network-libp2p = { path = "network-libp2p" }
rand = "0.3"
rlp = { git = "https://github.com/paritytech/parity-common" }
slog = "^2.2.3"
slog-term = "^2.4.0"
slog-async = "^2.3.0"
ssz = { path = "ssz" }
tokio = "0.1"

[dependencies.pairing]
git = "https://github.com/mmaker/pairing"
branch = "feature/hashing"

[patch.crates-io]
ring = { git = "https://github.com/paritytech/ring" }

[[bin]]
path = "lighthouse/main.rs"
name = "lighthouse"
