[workspace]
members = [
	"beacon_chain/attestation_validation",
	"beacon_chain/genesis",
	"beacon_chain/naive_fork_choice",
	"beacon_chain/spec",
	"beacon_chain/types",
	"beacon_chain/utils/bls",
	"beacon_chain/utils/boolean-bitfield",
	"beacon_chain/utils/hashing",
	"beacon_chain/utils/honey-badger-split",
	"beacon_chain/utils/slot_clock",
	"beacon_chain/utils/ssz",
	"beacon_chain/utils/vec_shuffle",
	"beacon_chain/validator_induction",
	"beacon_chain/validator_shuffling",
	"beacon_node",
	"beacon_node/db",
	"protos",
	"validator_client",
]
