[package]
name = "network"
version = "0.1.0"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"

[dependencies]
libp2p =  { git = "../libp2p" }
version = { path = "../version" }
types = { path = "../../eth2/types" }
