[package]
name = "swap_or_not_shuffle"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
hashing = { path = "../hashing" }

[dev-dependencies]
yaml-rust = "0.4.2"
hex = "0.3"
