[package]
name = "merkle_proof"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
ethereum-types = "0.6"
eth2_hashing = { path = "../eth2_hashing" }
lazy_static = "1.3.0"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
