[package]
name = "eth2_wallet_manager"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eth2_keystore = { path = "../eth2_keystore" }
eth2_wallet = { path = "../eth2_wallet" }

[dev-dependencies]
tempfile = "3.1.0"
