[package]
name = "websocket_server"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exit-future = "0.1.3"
futures = "0.1.25"
serde = "1.0"
serde_derive = "1.0"
slog = "^2.2.3"
tokio = "0.1.16"
types = { path = "../../eth2/types" }
ws = "0.9"
